server:
  servlet:
    port: 8080
    contextPath: /api

spring:
  application:
    name: myproman-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/myproman
    username: postgres
    password: nikhilKuyya

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
